# 项目端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: demo-interface

  datasource:
    bjxxk:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/bjxxk?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 50
      maxActive: 1000
      filters: stat,wall
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
    jsc:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/bjxxk_jsc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 50
      maxActive: 1000
      filters: stat,wall
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
    dp:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/dp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 50
      maxActive: 1000
      filters: stat,wall
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
    hcp:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/hcp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 50
      maxActive: 1000
      filters: stat,wall
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000



# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:com/dream/demo/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

# 统计接口调用次数定时任务cron表达式
task:
  cron: 0 0 23 * * ?


# 接口调用次数文件存储位置
file:
  path: D:\usr